language: python
python: 3.6.4
services: postgresql
env:
  - DJANGO=2.0.2 DB=postgresql DEBUG=False
  global:
    - secure: UJopXB1fOAYB1sk5C1Jn0e0jI0AcUOtrPnjfa/+eMKwwGg0Anj436WV8HxPLaK658zrcpU+08gPdUkYKPGYtVMA/HA0pWW2xc/l65uU5zqQHrAf5pzhE09/UgvMZjBf1udDah2r0AzBpqeZTJI5r9oj0+al5iF6vyXu0FxLcJfs3E7vcejofw50TDW4X9ax8Noarp+qRP6LmD4FpHpfMRifOAEfvDrGltzyUWnbBHW3SBiiXnTmbyJmJF5zjysFk3SSh61KEp8UGSz7Wl7eVFImUr7lEjdgAyQpWuxECscwGDs5Vji147ZgkVuryvw2LXsC07aCsITAc1jjqu1TydkOg3GmDo5d3cG1ptrxFA8fDax3B27p2bKWgZqmeKp4eOVa6UiXJGmdi3EoYYG65oqDdQXRzXKE9pDwElRcKDiXitUaPegNsX84cJusg1exArLkK2jPpzwF1CnWRIhQwXZb0rKhF/g/VUSOFcky+GOTD9FaeDA0kxWGQKHCONgpyabAjDLBS0WilMZnVnJIrzWPZ2/r/Whd6tfvwk1R2GnfwjMCgl7hWMTS5tirBr11NYRzPUJrrAT0J7/6mmFV6O/iVYTrmFSd7Q7wE/YhvCh1SGbVWU6T12CK2T1TJzlYoRxUr64ztEm7/GtzhY8Si1DNEIvsqwJ2kkLGKpPZJb2M=
install:
- pip install -r requirements.txt
before_script:
- psql -c "CREATE DATABASE cidb;" -U postgres
script:
- python manage.py test mainapp
