language: python

python: "3.6.4"

services: postgresql

env:
  - DJANGO=2.0.2 
  - DB=postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE cidb;" -U postgres

script: 
  - python manage.py test mainapp