# Generated by Django 2.0.2 on 2018-02-26 09:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(upload_to='static/mainapp/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=140)),
                ('profile_picture', models.ImageField(blank=True, upload_to='static/mainapp/images/')),
                ('city', models.CharField(max_length=30)),
                ('time_commitement', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=10), size=2)),
                ('events', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20), size=None)),
                ('categories', models.ManyToManyField(to='mainapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=140)),
                ('profile_picture', models.ImageField(blank=True, upload_to='static/mainapp/images/')),
                ('city', models.CharField(max_length=30)),
                ('category_list', models.ManyToManyField(to='mainapp.Category')),
                ('fav_org_list', models.ManyToManyField(to='mainapp.Organization')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.State')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.State'),
        ),
    ]
