# Generated by Django 2.0.2 on 2018-02-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=280)),
                ('date', models.DateTimeField()),
                ('event_image', models.ImageField(blank=True, upload_to='static/mainapp/images/')),
            ],
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='min_time_commitment',
            new_name='minimum_time_commitment',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='events',
        ),
        migrations.AddField(
            model_name='organization',
            name='events',
            field=models.ManyToManyField(to='mainapp.Events'),
        ),
    ]
