# Generated by Django 2.0.2 on 2018-02-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180226_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Organization'),
            preserve_default=False,
        ),
    ]
