# Generated by Django 2.0.2 on 2018-02-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20180227_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(upload_to='static/mainapp/images/category/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, upload_to='static/mainapp/images/event/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='static/mainapp/images/organization/'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='static/mainapp/images/volunteer/'),
        ),
    ]
